import Head from "next/head";

import styles from "@/styles/Home.module.scss";

import PixelatedImage from "@/components/PixelatedImage/page";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <PixelatedImage
          src={
            "https://a2-us.storyblok.com/f/1021482/4000x6000/4f5c0e7914/dsc_0767.jpg/m/0x1000/filters:quality(70):format(webp)"
          }
          blurrySrc={
            "https://a2-us.storyblok.com/f/1021482/4000x6000/4f5c0e7914/dsc_0767.jpg/m/0x15/filters:quality(20):format(webp)"
          }
        />
      </main>
    </>
  );
}
